### ISSUE TITLE
Possible to add option for --node-resolve

### ISSUE THREAD

**Issue by herrKlein** [Manish3323/web-test-runner#4] opened 2024-02-02 13:14 UTC
Hi,

If I run me tests within the extension 
`node_modules/.bin/web-test-runner /Users/patrickklein/Projects/QTI/QTI-components/tests/qti-transformers.test.ts`
I got the following error
`Failed to fetch dynamically imported module: http://localhost:8000/QTI-components/tests/qti-transformers.test.ts?wtr-session-id=VE7-LDLxG02k3HkKYSaeP`

I can run met web tests from npm with the following arguments:

`web-test-runner \"tests/**/*.test.ts\" --node-resolve --watch`

I think this is because of the argument `--node-resolve`
Is it possible to configure your extension to use --node-resolve ?

**Comment by Manish3323** [comment] 2024-02-02 13:33
Could you provide me reproducible repo with minimum required files.. I'll
try to set it up locally and test it out..

That would help me to solve it quickly.

Thanks for trying it out

**Comment by Manish3323** [comment] 2024-02-03 09:02
Okay, i think if you configure the nodeResolve flag in the wtr config.js file.. the extension plugin would pick it up.

currently you are running test like 
```
web-test-runner \"tests/**/*.test.ts\" --node-resolve --watch
```

Try appending that flag to the wtr config.. it should work, since when extension triggers that web test runner command, wtr picks the configuration file before executing the tests.
```
{
 ...
 nodeResolve: true,
 ...
}
```
let me know if that works..

I really want to keep the extension as generic as possible & not pass specific extra args from within the extension, Ideally it should be driven by the extension user's workspace configuration.

**Comment by Manish3323** [comment] 2024-02-07 15:54
Make sure to close this issue, if it works ? @herrKlein

**Closed as completed** 2024-02-17 07:33 UTC
